image_preprocessing:
  description: Prepare the image for analysis by resizing, normalizing, and enhancing
    contrast.
  expected_output: A preprocessed image ready for further analysis.
  agent: Image Preprocessing Agent
  context_task_names: []
element_detection:
  description: Use object detection algorithms to identify and locate elements within
    the image {{image}}.
  expected_output: A list of detected elements with their positions.
  agent: Element Detection Agent
  context_task_names:
  - Image Preprocessing
layout_analysis:
  description: Analyze the spatial relationships between detected elements to summarize
    the layout.
  expected_output: A summary of the layout highlighting spatial relationships.
  agent: Layout Analysis Agent
  context_task_names:
  - Element Detection
text_extraction:
  description: Extract textual content from the image {{image}} using Optical Character
    Recognition (OCR).
  expected_output: Extracted textual content from the image.
  agent: Text Extraction Agent
  context_task_names:
  - Image Preprocessing
text_summarization:
  description: Summarize the extracted textual content to highlight key information.
  expected_output: A summary of the extracted text highlighting key information.
  agent: Text Summarization Agent
  context_task_names:
  - Text Extraction
information_integration:
  description: Combine the summarized layout and textual content into a coherent report.
  expected_output: A cohesive report integrating layout analysis and textual content.
  agent: Information Integration Agent
  context_task_names:
  - Layout Analysis
  - Text Summarization
