extract_text_from_image:
  description: Use the Text Extraction Tool to extract readable text from the image
    {{image_path}}.
  expected_output: Extracted textual information from the image, if any.
  agent: text_extraction_agent
  context_task_names: []
identify_object_locations:
  description: Use the Object Location Tool to identify and describe the positions
    of objects within the image {{image_path}}.
  expected_output: Detailed information about object locations and their spatial relationships
    in the image.
  agent: object_location_agent
  context_task_names: []
interpret_image_content:
  description: Use the outputs from the Text Extraction Tool and Object Location Tool
    to provide a high-level interpretation of the image content.
  expected_output: A comprehensive understanding or interpretation of the image, including
    spatial arrangements, interactions between objects, and any textual information
    present.
  agent: image_interpretation_agent
  context_task_names:
  - Extract Text from Image
  - Identify Object Locations
